gyro:
  class: Serial
  port: /tmp/tty_gyro
  filebase: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas/test_data/status_screen/ar20240528_2000.GYRO

sbe48:
  class: Serial
  port: /tmp/tty_sbe48
  filebase: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas/test_data/status_screen/ar20240528_2000.SBE48