gyro:
  class: UDP
  port: 55101
  filebase: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas/test_data/status_screen/ar20240528_2000.GYRO

sbe48:
  class: UDP
  port: 55001
  filebase: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas/test_data/status_screen/ar20240528_2000.SBE48